# 生产环境
spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: aliyunroot
    password:
    url: jdbc:mysql://pjieyi.mysql.polardb.cn-chengdu.rds.aliyuncs.com/user_center

